title: "Perspektywy rynku domen, raport: 2024.digitname.com"
description: "Jak zmieniał się rynek domen w ostatniej dekadzie? Jak zmieni się rynek do roku 2030? Jak zmieni się internet do roku 2050?"
mermaid:
  src: "mermaid.js"
plugins:
  - "jekyll-github-metadata"  
  - "jekyll-readme-index"
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
